import { useEffect, type JSX } from 'react'

import {
  AlertCircle,
  CheckCircle2,
  Clock,
  Database,
  Loader2,
  RefreshCw,
  Sparkles
} from 'lucide-react'

import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import { getApi } from '@/lib/auth/auth-bridge'
import type { MacTitlebarStyles } from '@/features/notes/notes-app-types'
import type { NotesAppViewModel } from '@/features/notes/app-state/useNotesApp'

export type EmbeddingsSettingsViewProps = {
  isMacNotelab: boolean
  macTitlebarStyles: MacTitlebarStyles
  workspacePath: string | null
  guestMode?: boolean
  isLoggedIn: boolean
  indexingStatus: NotesAppViewModel['indexingStatus']
  refreshIndexingStatus: NotesAppViewModel['refreshIndexingStatus']
  runIndexPending: NotesAppViewModel['runIndexPending']
  runReindexAll: NotesAppViewModel['runReindexAll']
}

function StatusIcon({ state }: { state: string }): JSX.Element {
  if (state === 'indexing')
    return <Loader2 className="size-3.5 shrink-0 animate-spin text-blue-500" />
  if (state === 'indexed') return <CheckCircle2 className="size-3.5 shrink-0 text-green-500" />
  if (state === 'error') return <AlertCircle className="size-3.5 shrink-0 text-destructive" />
  return <Clock className="text-muted-foreground size-3.5 shrink-0" />
}

export function EmbeddingsSettingsView({
  isMacNotelab,
  macTitlebarStyles,
  workspacePath,
  guestMode,
  isLoggedIn,
  indexingStatus,
  refreshIndexingStatus,
  runIndexPending,
  runReindexAll
}: EmbeddingsSettingsViewProps): JSX.Element {
  // Load status when the panel mounts.
  useEffect(() => {
    void refreshIndexingStatus()
  }, [refreshIndexingStatus])

  const { notes, pendingCount, indexedCount, running } = indexingStatus
  const totalCount = notes.length
  const errorCount = notes.filter((n) => n.state === 'error').length
  const indexedPercent = totalCount > 0 ? Math.round((indexedCount / totalCount) * 100) : 0
  const showDebug = import.meta.env.DEV

  const disabled = !isLoggedIn || guestMode || running

  return (
    <div
      className="mx-auto flex w-full max-w-3xl flex-col gap-6 p-6"
      style={isMacNotelab ? macTitlebarStyles.noDrag : undefined}
    >
      {/* Header */}
      <div className="flex flex-col gap-1">
        <div className="flex items-center gap-2">
          <Sparkles className="text-muted-foreground size-5 shrink-0" aria-hidden />
          <h2 className="text-foreground text-lg font-semibold tracking-tight">Note Indexing</h2>
        </div>
        <p className="text-muted-foreground text-sm leading-relaxed">
          Index your notes and drawings to enable AI-powered search. Content is chunked and embedded
          via local Ollama or your Cloudflare Worker using the{' '}
          <span className="text-foreground font-medium">bge-m3</span> model, then stored in a
          workspace-local Vectra index.
        </p>
      </div>

      {/* Sign-in required notice */}
      {(!isLoggedIn || guestMode) && (
        <div className="border-border bg-muted/40 flex items-start gap-3 rounded-lg border p-4">
          <AlertCircle className="text-muted-foreground mt-0.5 size-4 shrink-0" aria-hidden />
          <p className="text-muted-foreground text-sm leading-relaxed">
            Sign in with GitHub to enable indexing. Embeddings are generated by the server and
            require an authenticated session.
          </p>
        </div>
      )}

      {/* Summary card */}
      {totalCount > 0 && (
        <div className="border-border flex flex-col gap-3 rounded-lg border p-4">
          <div className="flex items-center justify-between gap-2">
            <span className="text-foreground text-sm font-medium">
              {indexedCount} / {totalCount} indexed
            </span>
            <span className="text-muted-foreground text-xs">{indexedPercent}%</span>
          </div>
          {/* Progress bar */}
          <div className="bg-muted h-1.5 w-full overflow-hidden rounded-full">
            <div
              className={cn(
                'h-full rounded-full transition-all duration-500',
                errorCount > 0 ? 'bg-destructive' : 'bg-primary'
              )}
              style={{ width: `${indexedPercent}%` }}
            />
          </div>
          <div className="text-muted-foreground flex gap-4 text-xs">
            {pendingCount > 0 && <span>{pendingCount} pending</span>}
            {errorCount > 0 && <span className="text-destructive">{errorCount} failed</span>}
            {running && <span className="text-blue-500">Indexing…</span>}
          </div>
        </div>
      )}

      {/* Action buttons */}
      <div className="flex flex-wrap gap-3">
        <Button
          type="button"
          variant="outline"
          disabled={disabled || pendingCount === 0}
          onClick={() => void runIndexPending()}
          className="gap-2"
          title={
            !isLoggedIn || guestMode
              ? 'Sign in to enable indexing'
              : pendingCount === 0
                ? 'No pending notes'
                : undefined
          }
        >
          {running ? (
            <Loader2 className="size-4 animate-spin" aria-hidden />
          ) : (
            <Sparkles className="size-4" aria-hidden />
          )}
          Index Pending{pendingCount > 0 ? ` (${pendingCount})` : ''}
        </Button>

        {showDebug ? (
          <Button
            type="button"
            variant="outline"
            disabled={disabled || totalCount === 0}
            onClick={() => void runReindexAll()}
            className="gap-2"
            title={
              !isLoggedIn || guestMode
                ? 'Sign in to enable indexing'
                : totalCount === 0
                  ? 'No notes to index'
                  : undefined
            }
          >
            <RefreshCw className={cn('size-4', running && 'animate-spin')} aria-hidden />
            Reindex All
          </Button>
        ) : null}

        <Button
          type="button"
          variant="ghost"
          disabled={running}
          onClick={() => void refreshIndexingStatus()}
          className="gap-2"
          title="Refresh status"
        >
          <RefreshCw className="size-4" aria-hidden />
          Refresh
        </Button>

        {showDebug ? (
          <Button
            type="button"
            variant="ghost"
            disabled={!workspacePath}
            onClick={() => {
              if (!workspacePath) return
              const api = getApi()
              void api?.embeddings?.dumpIndex?.({ workspacePath }).then((result) => {
                if (!result) return
                if (!result.ok) {
                  console.error('[embeddings] dumpIndex failed:', result.error)
                  return
                }
                console.group(
                  `[embeddings] Vectra dump — ${result.totalDocuments} document(s), ${result.totalChunks} chunk(s)`
                )
                for (const document of result.documents) {
                  console.log(document)
                }
                console.groupEnd()
              })
            }}
            className="gap-2"
            title="Dump the current workspace index to DevTools console"
          >
            <Database className="size-4" aria-hidden />
            Dump to Console
          </Button>
        ) : null}
      </div>

      {/* Per-note list */}
      {showDebug && notes.length > 0 && (
        <div className="flex flex-col gap-1">
          <h3 className="text-muted-foreground mb-1 text-xs font-medium uppercase tracking-wider">
            Notes
          </h3>
          <div className="border-border divide-border divide-y rounded-lg border">
            {notes.map((n) => (
              <div key={n.note} className="flex items-center gap-3 px-3 py-2">
                <StatusIcon state={n.state} />
                <span className="text-foreground min-w-0 flex-1 truncate text-sm">
                  {n.title.trim() || 'Untitled'}
                </span>
                <span className="text-muted-foreground shrink-0 text-xs capitalize">
                  {n.kind === 'drawing' ? 'drawing' : null}
                </span>
                {n.state === 'error' && n.error && (
                  <span className="text-destructive max-w-[200px] truncate text-xs" title={n.error}>
                    {n.error}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {totalCount === 0 && !running && (
        <p className="text-muted-foreground text-sm">
          No notes found. Create a note and click Refresh to see the indexing status.
        </p>
      )}
    </div>
  )
}
