"use client"

import { AlertCircleIcon, BotIcon, CheckIcon } from "lucide-react"
import { nanoid } from "nanoid"
import * as React from "react"
import { toast } from "sonner"
import { readTextFile, writeTextFile } from "@tauri-apps/plugin-fs"
import {
  Conversation,
  ConversationContent,
  ConversationEmptyState,
  ConversationScrollButton,
} from "@/components/ai/conversation"
import {
  Message,
  MessageContent,
  MessageResponse,
} from "@/components/ai/message"
import {
  Reasoning,
  ReasoningContent,
  ReasoningTrigger,
} from "@/components/ai/reasoning"
import {
  LocalModelSelectorEmptyState,
  ModelSelector,
  ModelSelectorContent,
  ModelSelectorEmpty,
  ModelSelectorGroup,
  ModelSelectorInput,
  ModelSelectorItem,
  ModelSelectorList,
  ModelSelectorLogo,
  ModelSelectorName,
  ModelSelectorTrigger,
} from "@/components/ai/model-selector"
import {
  PromptInput,
  PromptInputBody,
  PromptInputButton,
  PromptInputFooter,
  type PromptInputMessage,
  PromptInputSubmit,
  PromptInputTextarea,
  PromptInputTools,
} from "@/components/ai/prompt-input"
import { Suggestion, Suggestions } from "@/components/ai/suggestion"
import Shimmer from "@/components/ai/shimmer"
import { getCurrentWorkspace } from "@/lib/workspace"
import { isSameFilePath, useActiveFilePath } from "@/lib/wikilink-utils"
import {
  type CliChatMessage,
  type CliProvider,
  type CliProviderModel,
  listCliProviderModels,
  listCliProviders,
  streamCliChat,
} from "@/lib/cli-chat"

type ChatEntry = {
  id: string
  role: "user" | "assistant"
  content: string
  thinking?: string
  state: "submitted" | "ready" | "streaming" | "error"
}

const suggestions = [
  "Summarize the current note into key takeaways.",
  "Turn these ideas into an action plan.",
  "Help me brainstorm next steps for this project.",
  "Rewrite this in a clearer, more concise way.",
]

const assistantWelcome =
  "Choose an installed CLI provider and start chatting. Responses are generated by the local Codex, OpenCode, or Claude CLI."

const MAX_ACTIVE_NOTE_CONTEXT_CHARS = 40_000
const NOTE_CONTENT_EXTERNAL_CHANGED_EVENT = "note-content-external-changed"
const NOTE_CONTENT_PROPOSAL_EVENT = "note-content-proposal"

function isActiveNoteUpdateRequest(content: string) {
  return (
    /\b(update|edit|rewrite|replace|write|create|turn|make)\b/i.test(content) &&
    /\b(this|current|active)\s+(note|file|document)\b/i.test(content)
  )
}

function stripAssistantMarkdownResponse(content: string) {
  const trimmed = content.trim()
  if (!trimmed) return null

  const fencedMarkdown = trimmed.match(/```(?:markdown|md)?\s*([\s\S]*?)```/i)
  if (fencedMarkdown?.[1]?.trim()) {
    return fencedMarkdown[1].trim()
  }

  const headingIndex = trimmed.search(/^#{1,6}\s+\S/m)
  if (headingIndex >= 0) {
    return trimmed.slice(headingIndex).trim()
  }

  if (/^(markdown|md)\s*\n/i.test(trimmed)) {
    return trimmed.replace(/^(markdown|md)\s*\n+/i, "").trim()
  }

  return null
}

function extractThinkingLine(message: string) {
  const raw = message.trim()
  if (!raw) return null
  if (/^(starting|spawned|stdout:|.*process exited\b)/i.test(raw)) return null

  const line = raw.replace(/^stderr:\s*/i, "").trim()
  if (!line) return null

  if (
    /^(OpenAI Codex|[-]{4,}|workdir:|model:|provider:|approval:|sandbox:|reasoning |session id:|user$|User:|exec$|succeeded in|tokens used|codex$)/i.test(
      line,
    )
  ) {
    return null
  }
  if (/^(\/|[A-Za-z0-9_.-]+\/|src\/|target\/|Cargo\.|Info\.plist|binaries$|icons$|native$|capabilities$|entitlements$|gen$|tauri\.conf\.json$)/.test(line)) {
    return null
  }
  if (line.includes(":") && /\b(src|target|apps|packages|docs)\//.test(line)) {
    return null
  }
  if (!/[A-Za-z]/.test(line) || !/\s/.test(line)) {
    return null
  }

  return line
}

function appendThinkingLog(current: string | undefined, next: string) {
  const thinkingLine = extractThinkingLine(next)
  if (!thinkingLine) return current ?? ""
  const line = `- ${thinkingLine}`
  if (!current) return line
  if (current.includes(line)) return current
  return `${current}\n${line}`
}

function AssistantActivity({
  content,
  isStreaming,
}: {
  content: string
  isStreaming: boolean
}) {
  if (content.trim()) {
    return <MessageResponse>{content}</MessageResponse>
  }

  if (!isStreaming) {
    return null
  }

  return (
    <div className="flex items-center gap-2 text-xs text-muted-foreground">
      <Shimmer className="h-2 w-2 rounded-full" duration={1} />
      <Shimmer className="h-2 w-2 rounded-full" duration={1.2} />
      <Shimmer className="h-2 w-2 rounded-full" duration={1.4} />
      <span>Preparing response...</span>
    </div>
  )
}

function buildCliMessages(messages: ChatEntry[]): CliChatMessage[] {
  return messages
    .filter(message => message.state !== "error")
    .map(message => ({
      role: message.role,
      content: message.content,
    }))
}

function buildContextMessage({
  activeFileContent,
  activeFilePath,
  workspace,
}: {
  activeFileContent: string | null
  activeFilePath: string | null
  workspace: string | null
}): CliChatMessage {
  const lines = [
    "You are running inside Mica chat.",
    workspace ? `Current workspace: ${workspace}` : "No workspace is currently open.",
    activeFilePath
      ? `Current active note/file: ${activeFilePath}`
      : "No active note/file is currently selected.",
  ]

  if (activeFileContent !== null) {
    const content =
      activeFileContent.length > MAX_ACTIVE_NOTE_CONTEXT_CHARS
        ? `${activeFileContent.slice(0, MAX_ACTIVE_NOTE_CONTEXT_CHARS)}\n\n[Active file truncated after ${MAX_ACTIVE_NOTE_CONTEXT_CHARS} characters.]`
        : activeFileContent

    lines.push(
      "When the user refers to the current note, use this active file content:",
      "```",
      content,
      "```",
    )
  }

  return {
    role: "system",
    content: lines.join("\n"),
  }
}

const ChatMessages = React.memo(function ChatMessages({
  availableProviderCount,
  messages,
}: {
  availableProviderCount: number
  messages: ChatEntry[]
}) {
  return (
    <Conversation className="min-h-0 flex-1 border-b text-xs">
      <ConversationContent>
        {messages.length ? (
          messages.map(message => (
            <Message from={message.role} key={message.id}>
              <MessageContent
                className={`text-xs leading-5 [&_.prose]:text-xs [&_p]:leading-5 [&_li]:leading-5 ${
                  message.role === "user" ? "gap-0 group-[.is-user]:px-3 group-[.is-user]:py-2" : ""
                }`}
              >
                {message.role === "assistant" && message.thinking ? (
                  <Reasoning
                    className="mb-2 text-xs"
                    defaultOpen
                    isStreaming={message.state === "submitted" || message.state === "streaming"}
                  >
                    <ReasoningTrigger
                      className="text-xs"
                      getThinkingMessage={(isStreaming, duration) => {
                        if (isStreaming) {
                          return <Shimmer duration={1}>Setting up CLI run...</Shimmer>
                        }
                        return (
                          <p className="text-xs">
                            Setup finished
                            {duration ? ` in ${duration} seconds` : ""}
                          </p>
                        )
                      }}
                    />
                    <ReasoningContent className="mt-2 text-xs leading-5">{message.thinking}</ReasoningContent>
                  </Reasoning>
                ) : null}
                {message.role === "assistant" ? (
                  <AssistantActivity
                    content={message.content}
                    isStreaming={message.state === "submitted" || message.state === "streaming"}
                  />
                ) : (
                  <MessageResponse>{message.content}</MessageResponse>
                )}
              </MessageContent>
            </Message>
          ))
        ) : (
          <ConversationEmptyState
            description={
              availableProviderCount
                ? assistantWelcome
                : "Install Codex, OpenCode, or Claude Code and refresh providers to start chatting here."
            }
            icon={
              availableProviderCount ? (
                <BotIcon className="size-10 opacity-40" />
              ) : (
                <AlertCircleIcon className="size-10 opacity-40" />
              )
            }
            title={availableProviderCount ? "CLI chat is ready" : "No CLI providers available"}
          />
        )}
      </ConversationContent>
      <ConversationScrollButton />
    </Conversation>
  )
})

const ChatComposer = React.memo(function ChatComposer({
  availableProviders,
  isChatDisabled,
  modelsLoading,
  providersLoading,
  onSend,
  selectedModel,
  selectedModelId,
  selectedProvider,
  selectedProviderId,
  providerModels,
  setModelSelectorOpen,
  setSelectedModelId,
  setSelectedProviderId,
  status,
}: {
  availableProviders: CliProvider[]
  isChatDisabled: boolean
  modelsLoading: boolean
  providersLoading: boolean
  onSend: (content: string) => Promise<void>
  selectedModel: CliProviderModel | undefined
  selectedModelId: string
  selectedProvider: CliProvider | undefined
  selectedProviderId: string
  providerModels: CliProviderModel[]
  setModelSelectorOpen: React.Dispatch<React.SetStateAction<boolean>>
  setSelectedModelId: React.Dispatch<React.SetStateAction<string>>
  setSelectedProviderId: React.Dispatch<React.SetStateAction<string>>
  status: "submitted" | "streaming" | "ready" | "error"
}) {
  const [text, setText] = React.useState("")
  const [providerSelectorOpen, setProviderSelectorOpen] = React.useState(false)
  const [modelSelectorOpen, setLocalModelSelectorOpen] = React.useState(false)

  const handleProviderOpenChange = React.useCallback(
    (open: boolean) => {
      setProviderSelectorOpen(open)
      setModelSelectorOpen(open)
    },
    [setModelSelectorOpen],
  )

  const handleModelOpenChange = React.useCallback(
    (open: boolean) => {
      setLocalModelSelectorOpen(open)
      setModelSelectorOpen(open)
    },
    [setModelSelectorOpen],
  )

  const handleSubmit = React.useCallback(
    async (message: PromptInputMessage) => {
      if (message.files?.length) {
        toast("Attachments are not sent to CLI providers yet.", {
          description: "The sidebar chat currently sends text only.",
        })
      }

      const nextText = message.text || ""
      setText("")
      await onSend(nextText)
    },
    [onSend],
  )

  const handleSuggestionClick = React.useCallback(
    async (suggestion: string) => {
      setText("")
      await onSend(suggestion)
    },
    [onSend],
  )

  React.useEffect(() => {
    if (!selectedProviderId && text) {
      setText("")
    }
  }, [selectedProviderId, text])

  return (
    <div className="shrink-0 space-y-4 px-4 pt-4 pb-4">
      <Suggestions>
        {suggestions.map(suggestion => (
          <Suggestion
            key={suggestion}
            onClick={() => void handleSuggestionClick(suggestion)}
            suggestion={suggestion}
          />
        ))}
      </Suggestions>

      <PromptInput onSubmit={handleSubmit}>
        <PromptInputBody>
          <PromptInputTextarea
            onChange={event => setText(event.target.value)}
            placeholder={
              selectedProvider
                ? `Message ${selectedProvider.name}${selectedModel ? ` / ${selectedModel.name}` : ""}...`
                : "Choose a CLI provider to start chatting..."
            }
            value={text}
          />
        </PromptInputBody>
        <PromptInputFooter>
          <PromptInputTools>
            <ModelSelector onOpenChange={handleProviderOpenChange} open={providerSelectorOpen}>
              <ModelSelectorTrigger asChild>
                <PromptInputButton>
                  {selectedProvider ? (
                    <ModelSelectorLogo provider={selectedProvider.logoProvider} />
                  ) : null}
                  <ModelSelectorName>
                    {selectedProvider?.name ?? "Choose provider"}
                  </ModelSelectorName>
                </PromptInputButton>
              </ModelSelectorTrigger>
              <ModelSelectorContent>
                <ModelSelectorInput placeholder="Search providers..." />
                <ModelSelectorList>
                  {!availableProviders.length && !providersLoading ? (
                    <LocalModelSelectorEmptyState
                      onNavigateToSettings={() => handleProviderOpenChange(false)}
                    />
                  ) : null}
                  {availableProviders.length ? (
                    <>
                      <ModelSelectorEmpty>No matching providers.</ModelSelectorEmpty>
                      <ModelSelectorGroup heading="CLI Providers">
                        {availableProviders.map(provider => (
                          <ModelSelectorItem
                            key={provider.id}
                            onSelect={() => {
                              setSelectedProviderId(provider.id)
                              handleProviderOpenChange(false)
                            }}
                            value={`${provider.name} ${provider.id}`}
                          >
                            <ModelSelectorLogo provider={provider.logoProvider} />
                            <ModelSelectorName>{provider.name}</ModelSelectorName>
                            {selectedProvider?.id === provider.id ? (
                              <CheckIcon className="ml-auto size-4" />
                            ) : (
                              <div className="ml-auto size-4" />
                            )}
                          </ModelSelectorItem>
                        ))}
                      </ModelSelectorGroup>
                    </>
                  ) : null}
                </ModelSelectorList>
              </ModelSelectorContent>
            </ModelSelector>
            {selectedProvider ? (
              <ModelSelector onOpenChange={handleModelOpenChange} open={modelSelectorOpen}>
                <ModelSelectorTrigger asChild>
                  <PromptInputButton disabled={modelsLoading || !providerModels.length}>
                    <ModelSelectorName>
                      {modelsLoading ? "Loading models..." : selectedModel?.name ?? "Choose model"}
                    </ModelSelectorName>
                  </PromptInputButton>
                </ModelSelectorTrigger>
                <ModelSelectorContent>
                  <ModelSelectorInput placeholder={`Search ${selectedProvider.name} models...`} />
                  <ModelSelectorList>
                    <ModelSelectorEmpty>No matching models.</ModelSelectorEmpty>
                    <ModelSelectorGroup heading={`${selectedProvider.name} Models`}>
                      {providerModels.map(model => (
                        <ModelSelectorItem
                          key={model.id}
                          onSelect={() => {
                            setSelectedModelId(model.id)
                            handleModelOpenChange(false)
                          }}
                          value={`${model.name} ${model.id}`}
                        >
                          <ModelSelectorName>{model.name}</ModelSelectorName>
                          {selectedModelId === model.id ? (
                            <CheckIcon className="ml-auto size-4" />
                          ) : (
                            <div className="ml-auto size-4" />
                          )}
                        </ModelSelectorItem>
                      ))}
                    </ModelSelectorGroup>
                  </ModelSelectorList>
                </ModelSelectorContent>
              </ModelSelector>
            ) : null}
          </PromptInputTools>
          <PromptInputSubmit disabled={isChatDisabled || !text.trim()} status={status} />
        </PromptInputFooter>
      </PromptInput>
    </div>
  )
})

export function Chat({
  onConversationStateChange,
}: {
  onConversationStateChange?: (hasConversation: boolean) => void
} = {}) {
  const activeFilePath = useActiveFilePath()
  const [workspace, setWorkspace] = React.useState<string | null>(() => getCurrentWorkspace())
  const [activeFileContent, setActiveFileContent] = React.useState<string | null>(null)
  const [providers, setProviders] = React.useState<CliProvider[]>([])
  const [providerModels, setProviderModels] = React.useState<CliProviderModel[]>([])
  const [providersLoading, setProvidersLoading] = React.useState(true)
  const [modelsLoading, setModelsLoading] = React.useState(false)
  const [messages, setMessages] = React.useState<ChatEntry[]>([])
  const [status, setStatus] = React.useState<"submitted" | "streaming" | "ready" | "error">(
    "ready",
  )
  const [selectedProviderId, setSelectedProviderId] = React.useState("")
  const [selectedModelId, setSelectedModelId] = React.useState("")
  const [_modelSelectorOpen, setModelSelectorOpen] = React.useState(false)

  const availableProviders = React.useMemo(
    () => providers.filter(provider => provider.installed),
    [providers],
  )

  const selectedProvider = React.useMemo(
    () =>
      availableProviders.find(provider => provider.id === selectedProviderId) ??
      availableProviders[0],
    [availableProviders, selectedProviderId],
  )

  const selectedModel = React.useMemo(
    () => providerModels.find(model => model.id === selectedModelId) ?? providerModels[0],
    [providerModels, selectedModelId],
  )

  React.useEffect(() => {
    const handleWorkspaceChanged = () => setWorkspace(getCurrentWorkspace())
    window.addEventListener("workspace-changed", handleWorkspaceChanged)
    return () => window.removeEventListener("workspace-changed", handleWorkspaceChanged)
  }, [])

  React.useEffect(() => {
    let cancelled = false

    if (!activeFilePath) {
      setActiveFileContent(null)
      return
    }

    readTextFile(activeFilePath)
      .then(content => {
        if (!cancelled) {
          setActiveFileContent(content)
        }
      })
      .catch(error => {
        console.debug("[cli-chat] active file content unavailable", {
          activeFilePath,
          error,
        })
        if (!cancelled) {
          setActiveFileContent(null)
        }
      })

    return () => {
      cancelled = true
    }
  }, [activeFilePath])

  React.useEffect(() => {
    const handleExternalNoteContentChanged = (event: Event) => {
      const detail = (event as CustomEvent<{ content?: string | null; path?: string | null }>).detail
      if (
        activeFilePath &&
        detail?.path &&
        isSameFilePath(detail.path, activeFilePath) &&
        typeof detail.content === "string"
      ) {
        setActiveFileContent(detail.content)
      }
    }

    window.addEventListener(NOTE_CONTENT_EXTERNAL_CHANGED_EVENT, handleExternalNoteContentChanged)
    return () => {
      window.removeEventListener(NOTE_CONTENT_EXTERNAL_CHANGED_EVENT, handleExternalNoteContentChanged)
    }
  }, [activeFilePath])

  React.useEffect(() => {
    let cancelled = false
    setProvidersLoading(true)
    listCliProviders()
      .then(nextProviders => {
        if (!cancelled) {
          setProviders(nextProviders)
        }
      })
      .catch(error => {
        console.error("Failed to load CLI providers:", error)
        if (!cancelled) {
          setProviders([])
        }
      })
      .finally(() => {
        if (!cancelled) {
          setProvidersLoading(false)
        }
      })

    return () => {
      cancelled = true
    }
  }, [])

  React.useEffect(() => {
    if (!availableProviders.length) {
      if (selectedProviderId) {
        setSelectedProviderId("")
      }
      return
    }

    if (!availableProviders.some(provider => provider.id === selectedProviderId)) {
      setSelectedProviderId(availableProviders[0]!.id)
    }
  }, [availableProviders, selectedProviderId])

  React.useEffect(() => {
    if (!selectedProvider) {
      setProviderModels([])
      setSelectedModelId("")
      return
    }

    let cancelled = false
    setModelsLoading(true)
    listCliProviderModels(selectedProvider.id)
      .then(models => {
        if (!cancelled) {
          setProviderModels(models)
          setSelectedModelId(current =>
            models.some(model => model.id === current) ? current : models[0]?.id ?? "",
          )
        }
      })
      .catch(error => {
        console.error("Failed to load CLI provider models:", error)
        if (!cancelled) {
          setProviderModels([])
          setSelectedModelId("")
        }
      })
      .finally(() => {
        if (!cancelled) {
          setModelsLoading(false)
        }
      })

    return () => {
      cancelled = true
    }
  }, [selectedProvider])

  const sendMessage = React.useCallback(
    async (content: string) => {
      if (!selectedProvider) {
        setModelSelectorOpen(true)
        toast.error("Choose an installed CLI provider before chatting.")
        return
      }

      const trimmedContent = content.trim()
      if (!trimmedContent) {
        return
      }

      const userMessage: ChatEntry = {
        id: nanoid(),
        role: "user",
        content: trimmedContent,
        state: "ready",
      }
      const assistantMessageId = nanoid()
      const assistantPlaceholder: ChatEntry = {
        id: assistantMessageId,
        role: "assistant",
        content: "",
        thinking: appendThinkingLog(
          undefined,
          `Preparing ${selectedProvider.name}${selectedModel ? ` with ${selectedModel.name}` : ""}`,
        ),
        state: "submitted",
      }

      const nextMessages = [...messages, userMessage]
      const contextMessage = buildContextMessage({
        activeFileContent,
        activeFilePath,
        workspace,
      })

      setMessages([...nextMessages, assistantPlaceholder])
      setStatus("submitted")

      let accumulated = ""
      let firstChunkReceived = false
      let hasPendingProposal = false
      const refreshedPaths = new Set<string>()
      const proposalTasks: Promise<void>[] = []

      const refreshExternalFile = async (path: string, source: string) => {
        if (refreshedPaths.has(path)) {
          return
        }
        refreshedPaths.add(path)

        console.debug("[cli-chat] refreshing changed file", {
          activeFilePath,
          path,
          source,
        })

        try {
          const updatedContent = await readTextFile(path)
          if (activeFilePath && isSameFilePath(path, activeFilePath)) {
            setActiveFileContent(updatedContent)
          }
          window.dispatchEvent(
            new CustomEvent(NOTE_CONTENT_EXTERNAL_CHANGED_EVENT, {
              detail: {
                content: updatedContent,
                path,
                source,
              },
            }),
          )
        } catch (error) {
          console.debug("[cli-chat] changed file refresh failed", {
            error,
            path,
            source,
          })
        }
      }

      const proposeExternalFileChange = async (path: string, source: string) => {
        console.debug("[cli-chat] preparing note change proposal", {
          activeFilePath,
          path,
          source,
        })

        try {
          const proposedContent = await readTextFile(path)
          const originalContent =
            activeFilePath && isSameFilePath(path, activeFilePath)
              ? activeFileContent ?? ""
              : ""

          if (originalContent && proposedContent !== originalContent) {
            await writeTextFile(path, originalContent)
            console.debug("[cli-chat] reverted disk change pending review", {
              path,
              source,
            })
          }

          window.dispatchEvent(
            new CustomEvent(NOTE_CONTENT_PROPOSAL_EVENT, {
              detail: {
                originalContent,
                path,
                proposedContent,
                source,
              },
            }),
          )
          hasPendingProposal = true
        } catch (error) {
          console.debug("[cli-chat] note change proposal failed", {
            error,
            path,
            source,
          })
          await refreshExternalFile(path, source)
        }
      }

      try {
        await streamCliChat({
          chatId: assistantMessageId,
          providerId: selectedProvider.id,
          model: selectedModel?.id ?? null,
          cwd: workspace,
          messages: [contextMessage, ...buildCliMessages(nextMessages)],
          smooth: { chunking: "word", delayInMs: 15 },
          onLog: payload => {
            setMessages(currentMessages =>
              currentMessages.map(message =>
                message.id === assistantMessageId
                  ? {
                      ...message,
                      thinking: appendThinkingLog(message.thinking, payload.message),
                    }
                  : message,
              ),
            )
          },
          onFileChanged: path => {
            if (activeFilePath && isSameFilePath(path, activeFilePath)) {
              hasPendingProposal = true
              proposalTasks.push(proposeExternalFileChange(path, "cli-change-detection"))
              return
            }
            void refreshExternalFile(path, "cli-change-detection")
          },
          onDelta: delta => {
            accumulated += delta
            if (!firstChunkReceived) {
              firstChunkReceived = true
              setStatus("streaming")
            }
            setMessages(currentMessages =>
              currentMessages.map(message =>
                message.id === assistantMessageId
                  ? { ...message, content: accumulated, state: "streaming" }
                  : message,
              ),
            )
          },
        })

        if (proposalTasks.length > 0) {
          await Promise.allSettled(proposalTasks)
        }

        if (
          activeFilePath &&
          refreshedPaths.size === 0 &&
          !hasPendingProposal &&
          isActiveNoteUpdateRequest(trimmedContent)
        ) {
          const markdownUpdate = stripAssistantMarkdownResponse(accumulated)
          if (markdownUpdate) {
            console.debug("[cli-chat] creating assistant markdown proposal", {
              activeFilePath,
              chars: markdownUpdate.length,
            })
            window.dispatchEvent(
              new CustomEvent(NOTE_CONTENT_PROPOSAL_EVENT, {
                detail: {
                  originalContent: activeFileContent ?? "",
                  path: activeFilePath,
                  proposedContent: markdownUpdate.endsWith("\n") ? markdownUpdate : `${markdownUpdate}\n`,
                  source: "assistant-markdown-fallback",
                },
              }),
            )
            hasPendingProposal = true
          } else {
            console.debug("[cli-chat] assistant markdown fallback skipped: no markdown payload", {
              activeFilePath,
            })
          }
        }

        if (activeFilePath) {
          await refreshExternalFile(activeFilePath, "active-file-fallback")
        }

        setMessages(currentMessages =>
          currentMessages.map(message =>
            message.id === assistantMessageId
              ? {
                  ...message,
                  content: accumulated.trim() || "No response returned.",
                  state: "ready",
                }
              : message,
          ),
        )
        setStatus("ready")
      } catch (error) {
        const message =
          error instanceof Error
            ? error.message
            : "Something went wrong while talking to the CLI provider."

        setMessages(currentMessages =>
          currentMessages.map(entry =>
            entry.id === assistantMessageId
              ? {
                  ...entry,
                  content: accumulated.trim()
                    ? `${accumulated.trim()}\n\n_${message}_`
                    : message,
                  state: "error",
                }
              : entry,
          ),
        )
        setStatus("error")
        toast.error("Chat failed", {
          description: message,
        })
      }
    },
    [activeFileContent, activeFilePath, messages, selectedModel, selectedProvider, workspace],
  )

  const isChatDisabled = !selectedProvider || status === "streaming"

  React.useEffect(() => {
    onConversationStateChange?.(messages.length > 0)
  }, [messages.length, onConversationStateChange])

  return (
    <div className="flex h-full min-h-0 w-full flex-col overflow-hidden">
      <ChatMessages availableProviderCount={availableProviders.length} messages={messages} />
      <ChatComposer
        availableProviders={availableProviders}
        isChatDisabled={isChatDisabled}
        modelsLoading={modelsLoading}
        providersLoading={providersLoading}
        onSend={sendMessage}
        selectedModel={selectedModel}
        selectedModelId={selectedModelId}
        selectedProvider={selectedProvider}
        selectedProviderId={selectedProviderId}
        providerModels={providerModels}
        setModelSelectorOpen={setModelSelectorOpen}
        setSelectedModelId={setSelectedModelId}
        setSelectedProviderId={setSelectedProviderId}
        status={status}
      />
    </div>
  )
}

export default Chat
